.github/workflows/commit-check.yml
=> fix: add multi commit check

app/controllers/client_controller.py, app/routes/__init__.py, app/schemas/client_register_dto.py, app/schemas/user_create_dto.py, app/usecases/register_client.py
this commit was lost sometime
QW-50
=> QW-50 Add client registration

requirements.txt
=> QW-111 specify pydantic-email version

seeders/seed_tariffs.py
raise prices and reduce opportunities
QW-110
=> QW-110 switch tariffs conditions

app/ai/inference.py, app/ai/model.py, app/models/client.py, app/usecases/inspect_product.py, requirements.txt
=> QW-85 Export ml model

app/controllers/defect_controller.py, app/routes/__init__.py
=> QW-85 Add defects controller

app/controllers/analytics_controller.py, app/usecases/get_analytics_summary.py, requirements.txt
=> QW-119 Add analytics controller and usecase

.env, app/ai/inference.py, app/controllers/inspection_controller.py, app/services/minio_client.py, requirements.txt
add MinIO, rebuild ai and inspection controller for it, add requirement into .txt and update .env for it
QW-85
=> QW-85 Add real images handling

app/usecases/register_client.py
=> QW-120 Fix register bug

app/config.py, app/controllers/auth_controller.py, app/usecases/login_user.py, requirements.txt
=> QW-122 Add jwt system

app/controllers/user_controller.py, app/schemas/sub_user_create_dto.py, app/usecases/create_sub_user.py
=> QW-121 Add subusers system

tests/dev_seed.py, tests/dev_unseed.py
Add license seed and unseed functions
QW-85
=> QW-85 Add license fixters

main.py, requirements.txt
=> QW-126 Add cors

app/controllers/__init__.py, app/controllers/auth_controller.py, app/controllers/client_controller.py, main.py
=> QW-126 Cors is disabled for auth and client endpoints

Dockerfile
=> feat: update docker

main.py
=> QW-126 Delete cors object initialization from main.py

app/controllers/user_controller.py
=> QW-126 Corsify user/me endpoint

start.sh
=> fix: starter wrong path

alembic.ini, app/config.py, docker-compose.yml
=> fix: hardcode server db

start.sh
=> fix: fix starter

docker-compose.yml
=> fix: fix docker compose

alembic.ini, app/config.py, docker-compose.yml, start.sh
=> fix: fix db link

.env
=> QW-137 Add db_url into dotenv

start.sh
=> QW-137 Fix git pulling in stash.sh

main.py
=> QW-137 change env for server

app/controllers/client_controller.py, main.py
=> QW-153 Corsify clients endpoint

main.py
=> QW-153 salam popolam allah help please

app/controllers/client_controller.py, main.py
=> QW-153 Trying to fix cors... Jesus please be better than allah

app/controllers/client_controller.py, main.py
=> QW-153 askdjfhjkdhasfgasdujofkj

main.py
=> QW-153 asfjfasdhasdf

app/controllers/client_controller.py, main.py
=> fixdfasfasasdf

docker-compose.yml
=> fix: fix compose

app/controllers/client_controller.py, main.py
=> fix: fix cors

app/ai/inference.py, app/controllers/inspection_controller.py, app/repositories/defect_repository.py, app/repositories/inspection_repository.py, app/repositories/product_repository.py, app/schemas/inspect_product_dto.py, app/usecases/inspect_product.py, app/usecases/register_client.py
=> QW-174 Add real inspection

app/ai/model.py
=> QW-174 fix yolo model import

Dockerfile
=> QW-174 Add libgl1 installing into dockerfile

Dockerfile
=> QW-174 add libglib2 installing into dockerfile

Dockerfile
=> QW-174 Add opencv installing into dockerfile

requirements.txt
=> QW-174 Add opencv dependence into requirements.txt

Dockerfile
=> QW-174 change dockerfile

app/ai/model.py
=> fix: fix model path

app/controllers/user_controller.py, app/schemas/camera/camera_update_dto.py
=> QW-188 add error codes into user controller
